### ISSUE TITLE
Allow otel trace ids to be output in logs

### ISSUE THREAD

**Issue by phillipuniverse** [DataDog/nginx-datadog#102]
Reading the [variables section of the docs](https://github.com/DataDog/nginx-datadog/blob/master/doc/API.md#variables), we can access `datadog_trace_id` and `datadog_span_id` which are integers. It would be great to be able to instead output the OpenTelemetry version of trace and span ids based on a hex string instead.

This would be similar to how `traceparent` works just with the ability to write those variables to logs.

Thanks!

**Comment by dmehala** [comment]
Hi @phillipuniverse 

I understand you would like to output the trace and span IDs in the OpenTelemetry format (hex strings) instead of the current Datadog format (decimal representation). Can you confirm?

**Comment by phillipuniverse** [comment]
@dmehala yes that is right.
