### ISSUE TITLE
Release for nginx version 1.26.2? 

### ISSUE THREAD

**Issue by kneufeld-pbp** [DataDog/nginx-datadog#118]
When will a release for Nginx `1.26.2` be available? 
Nginx 1.26.2 has been out since `12 Aug 2024`. What is the release cadence for including a new version of Nginx?

**Comment by dmehala** [comment]
Hello,
Good catch, I'll add 1.26.2 today. Thank you.

**Comment by kneufeld-pbp** [comment]
@dmehala, Will the release 1.3.0 be updated with a module binary for Nginx 1.26.2? When?
