### ISSUE TITLE
1.3.0 gives me "failed to extract a Datadog span request" for every request

### ISSUE THREAD

**Issue by janerikcarlsen** [DataDog/nginx-datadog#120]
Nginx version: 1.27.1
Architecture: amd64
nginx-datadog version: 1.3.0
Configuration: Plain, just importing the dd_nginx module like we have done before. 

After upgrading to 1.3.0, there is an error for each request: 

```
failed to extract a Datadog span request XXXXXXXXXXXX: [error code 11]: While extracting trace context, an error occurred: There's neither a trace ID nor a parent span ID to extract., client: <ip>, server: , request: "GET /health HTTP/1.1", host: "<ip>:<port>"
```

I see that version 1.3.0 uses https://github.com/DataDog/dd-trace-cpp/releases/tag/v1.0.0 which is currently in a pre-relase state. The PR https://github.com/DataDog/dd-trace-cpp/pull/131 contains refactorings for the `extract_or_create_span` function which seems to contain the error messaging we're seing. 

Our fix is to roll back to earlier releases of nginx and datadog-nginx

**Comment by dubloom** [comment]
Hey there,

It looks like the same problem as #116. Therefore, the good news is the bug has been fixed and the release is on its way.

I'll close this issue but do not hesitate to reopen it if you feel this is not solving your problem.
