### ISSUE TITLE
Feature request: arm64 binaries

### ISSUE THREAD

**Issue by mcuelenaere** [DataDog/nginx-datadog#31]
Would it be possible to provide arm64 binaries (or Docker images)? Is there anything blocking for getting nginx-datadog built for the arm64 architecture?

**Comment by dgoffredo** [comment]
Hi, Maurus. Please see [my response in a related issue][1].

Note that `dd-opentracing-cpp` is used by `nginx-opentracing`, which is older than `nginx-datadog`. As of a recent release, `nginx-datadog` now uses [dd-trace-cpp][2] instead.

Still, none of these Datadog C++ projects yet support ARM64.

[1]: https://github.com/DataDog/dd-opentracing-cpp/issues/264#issuecomment-1603095994
[2]: https://github.com/DataDog/dd-trace-cpp

**Comment by mcuelenaere** [comment]
Hi @dgoffredo, yes I'm aware of the `nginx-datadog` vs `dd-opentracing-cpp` differences. We've evaluated both in the past, but had to switch back to `dd-opentracing-cpp` due to some issue (can't remember what it was).

However now we're evaluating if we can run our setup on ARM64 and perhaps switching back to `nginx-datadog` might be easier in that regard, hence why I opened issues in both repos.

**Comment by dgoffredo** [comment]
Got it. I think that you can proceed in the same way as in [the other issue][1], by submitting this as a feature request via Datadog's Support system.

This is work that we can do, and will have to eventually. The question is when, and what the priority is relative to other work.

[1]: https://github.com/DataDog/dd-opentracing-cpp/issues/264#issuecomment-1603185913

**Comment by mcuelenaere** [comment]
Feature request filed!

**Comment by dgoffredo** [comment]
Thanks, let's leave this open, and I'll chase after whoever I need to internally.
