### ISSUE TITLE
Feature request: nginx 1.25 release 

### ISSUE THREAD

**Issue by vertex** [DataDog/nginx-datadog#32]
Hey there,  I was hoping you folks could build a release for nginx 1.25 please. See the ngnx release notes here: http://nginx.org/en/CHANGES

**Comment by dgoffredo** [comment]
Sure thing, will do this early next week.

**Comment by dgoffredo** [comment]
[v1.0.1][1] adds support for nginx's 1.25 docker images.

[1]: https://github.com/DataDog/nginx-datadog/releases/tag/v1.0.1

**Comment by vertex** [comment]
Thanks!  I'll close this and feel free to open it :)

**Comment by narasimhan-coverwallet** [comment]
Hello! Can we also support `v1.25.2`? :)

**Comment by dgoffredo** [comment]
Sure thing, I'll get working on a release.

**Comment by dgoffredo** [comment]
https://github.com/DataDog/nginx-datadog/releases/tag/v1.0.2

**Comment by narasimhan-coverwallet** [comment]
Thank you so much! We will start testing it right away and let you know if there are bugs.
