### ISSUE TITLE
Allow separate enable/disable of trace/span propagation vs trace/span export

### ISSUE THREAD

**Issue by phillipuniverse** [DataDog/nginx-datadog#39]
Originally opened at https://github.com/DataDog/dd-trace-cpp/issues/55 (wrong project).

I am just getting started on integrating this project for otel propagation (coming from the opentelemetry-cpp-config project which is too much in limbo). It looks like this has a similar issue in the default otel nginx instrumentation where I cannot enable tracing (extraction, injection, log messages) without also having the Datadog agent up to receive traces.

My use case is running locally, I want to be able to test trace propagation without exporting any of the spans that are generated from nginx.

I didn't see how this was possible in the current config, is it?

**Comment by phillipuniverse** [comment]
[dgoffredo](https://github.com/dgoffredo) from your [previous answer](https://github.com/DataDog/dd-trace-cpp/issues/55#issuecomment-1703074656) does `DD_TRACE_ENABLED` control _both_ propagation _and_ exports or only exports?

Said another way - if I have `DD_TRACE_ENABLED=false`, do my downstream services get trace headers like `X-Datadog-Trace-Id`

**Comment by dgoffredo** [comment]
The name "[report_traces][1]," of the underlying configuration option, is better than the name of the environment variable.

`DD_TRACE_ENABLED` controls only whether traces are sent to the Datadog agent. Regardless of its value, traces are still created in memory and are still propagated to services contacted by nginx.

[1]: https://github.com/DataDog/dd-trace-cpp/blob/e9b715d1c66f9dc4ccb3a0561475336fe92431af/src/datadog/tracer_config.h#L45-L50

**Comment by phillipuniverse** [comment]
@dgoffredo confirmed! Thanks so much, this was a big pain point for me coming from [the OpenTracing implementation](https://github.com/DataDog/dd-opentracing-cpp), really glad to see this issue fixed!

Thanks for shipping such great products!!
