### ISSUE TITLE
Latest 1.0.4 version breaks documented installation script

### ISSUE THREAD

**Issue by jfranzoi-gucci** [DataDog/nginx-datadog#52]
Hi, just wanted to share latest **1.0.4** version, which introduced artifacts for both `x86_64` and `arm64` architectures, broke installation script as documented on datadog docs website:
- site [here](https://docs.datadoghq.com/tracing/trace_collection/proxy_setup/?tab=nginx)
- source, script starting from [here](https://github.com/DataDog/documentation/blob/b8721b3ab28aefe9fda0120c4e468fb71ba4f0bf/content/en/tracing/trace_collection/proxy_setup/_index.md?plain=1#L311)

On my side, I just temporarily fixed the script to be run on previous **1.0.3** version, but going to align it with new naming strategy for assets download (eg: including architecture in file name).

Please let me know if you need me to provide a PR for the website docs once done.

Thank you.

**Comment by dmehala** [comment]
Hi,

Thank you for flagging the issue with the installation script following the 1.0.4 update. We are currently working to update the documentation to reflect the changes.

**Comment by dmehala** [comment]
Hi @jfranzoi-gucci,

It's fixed now, and we're putting guidelines in place to prevent future glitches. Thank you!
