### ISSUE TITLE
undefined symbol: ZSTD_isError on AL2023

### ISSUE THREAD

**Issue by gugaiz** [DataDog/nginx-datadog#53]
Hi,

I made some changes on my [forked branch ](https://github.com/DataDog/nginx-datadog/pull/54)to make the scripts work with the new AL2023 dist. I managed to build the module but when I try to run it on the AL2023  dist I am getting

```
# nginx -t -c /var/proxy/staging/nginx/nginx.conf
nginx: [emerg] dlopen() "/usr/lib64/nginx/modules/ngx_http_datadog_module.so" failed (/usr/lib64/nginx/modules/ngx_http_datadog_module.so: undefined symbol: ZSTD_isError) in /var/proxy/staging/nginx/nginx.conf:8
nginx: configuration file /var/proxy/staging/nginx/nginx.conf test failed
```

I checked and I have the zstd library installed

```
# rpm -qa | grep zstd
libzstd-1.5.5-1.amzn2023.0.1.x86_64
zstd-1.5.5-1.amzn2023.0.1.x86_64
libzstd-devel-1.5.5-1.amzn2023.0.1.x86_64
```

```
# ldconfig -p | grep -i ZSTD
	libzstd.so.1 (libc6,x86-64) => /lib64/libzstd.so.1
	libzstd.so (libc6,x86-64) => /lib64/libzstd.so
```

When running the command below I don't see the linkage of the ZSTD library in the module:
```
# ldd /usr/lib64/nginx/modules/ngx_http_datadog_module.so
	linux-vdso.so.1 (0x00007ffc4add5000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fca262ec000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fca25c00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fca263cd000)
```
```
$ cat nginx-version-info
ARCH=linux/amd64
NGINX_VERSION=1.24.0
BASE_IMAGE=amazonlinux:2023.2.20231113.0
NGINX_MODULES_PATH=/usr/share/nginx/modules
```

Any ideas of why is failing?

**Comment by dgoffredo** [comment]
Hi again, @gugaiz. Thanks for the contribution.

Every once and a while, usually when adding a new build target as you have done here, I have to add some exclusion options to libcurl's `./configure`.

We might make this exact change, or migrate over to using purely CMake-based configuration of libcurl.
