### ISSUE TITLE
Feature request: nginx 1.25.4 support

### ISSUE THREAD

**Issue by na-ji** [DataDog/nginx-datadog#62]
Hi! 

Same request as in #32, would it be possible to support the latest nginx version, please? 
Also, is there any plan to automate this support?

Thank you.

**Comment by dgoffredo** [comment]
Hi, @na-ji.

We would like to automate support for new nginx versions, but have not yet spent the time to implement a reliable system for it.

I'm thinking a CI job that consults either <nginx.org> or some mailing list to see when a new release happens, and then kicks off a job to build/test in that configuration. We use nginx's Docker images as a base for our builds and tests (at least for now), so there's also the question of when the nginx maintainers publish those images.

We'll look into adding support for nginx 1.25.4. It's usually just a matter of building and testing everything, and then publishing a new release.

**Comment by dgoffredo** [comment]
The new Alpine image is not playing nice. Here's a prereq: <https://github.com/DataDog/dd-trace-cpp/pull/99>.

After that it should be smooth sailing for a release.

**Comment by dgoffredo** [comment]
https://github.com/DataDog/nginx-datadog/pull/63

**Comment by dgoffredo** [comment]
See the 1.25.4 related artifacts in today's release: https://github.com/DataDog/nginx-datadog/releases/tag/v1.0.5

**Comment by na-ji** [comment]
> See the 1.25.4 related artifacts in today's release: [`v1.0.5` (release)](https://github.com/DataDog/nginx-datadog/releases/tag/v1.0.5)

Thank you very much!
