### ISSUE TITLE
Disable Trace Sending Conditionally

### ISSUE THREAD

**Issue by zackerydev** [DataDog/nginx-datadog#70]
👋🏻 Hello!

I have this module working well in our production environments.

However, I'm trying to figure out how to disable trace sending in our non prod environments.

I've tried `datadog_disable;` but that still spams our logs with "Error: Connection Refused".

We don't run the agents for tracing in our dev clusters, is there a way to disable trace sending entirely but still load the module? I could be missing something, I've tried `DD_TRACE_ENABLED` and a plethora of other options to no avail.

**Comment by zackerydev** [comment]
Hi!

I didn't mean to imply that it was broken - just that I was probably missing something.

And yes it looks like you are right, this is the log message:
```
2024/04/08 19:15:57 [error] 62#66: datadog: [error code 4] Error occurred during HTTP request for Remote Configuration: Error sending request with libcurl (Couldn't connect to server): Failed to connect to 10.1.140.232 port 8126 after 0 ms: Connection refused
```

**Comment by dmehala** [comment]
No worries. That's the nature of development; regressions can slip in from time to time.

If you're using version `v1.1.0`, you have the option to deactivate the feature by setting `DD_REMOTE_CONFIGURATION_ENABLED=false`. However, if you're on `v1.0.5`, I'm afraid there's no direct way to disable it. My recommendation would be to consider upgrading to `v1.1.0` for the best resolution.

**Comment by zackerydev** [comment]
Thanks @dmehala 

Is there a place I can see all the supported environment variables?

**Comment by dmehala** [comment]
Hi @zackerydev 

There's been no update in the last two weeks, were you able to fix your issue?
