### ISSUE TITLE
Feature Request: nginx 1.26.0 support

### ISSUE THREAD

**Issue by jlwt90** [DataDog/nginx-datadog#72]
Hello team, could we add support for nginx-1.26.0?
Thanks 🙇

**Comment by dmehala** [comment]
Hello,

The latest release now contains prebuilt binaries for NGINX `1.26.0`, check it out [here](https://github.com/DataDog/nginx-datadog/releases/tag/v1.1.0).

Keep me updated if you encounter any issues... or not 🙂.

Thank you.

**Comment by jlwt90** [comment]
Thank you! I'll test it out after holiday =)
