### ISSUE TITLE
NGINX_VERSION=1.22.1 make build fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by monelgordillo** [DataDog/nginx-datadog#74]
Getting "fatal: not a git repository (or any of the parent directories): .git"

NGINX_VERSION=1.22.1 make build

/var/www/html/nginx-datadog-1.1.0
total 120
drwxrwxr-x   12 root     root          4096 Apr  2 13:36 .
drwxrwxrwx    1 nginx    nginx         4096 Apr 30 17:50 ..
drwxrwxr-x    2 root     root          4096 Apr  2 13:36 .circleci
lrwxrwxrwx    1 root     root            26 Apr  2 13:36 .clang-format -> dd-trace-cpp/.clang-format
-rw-rw-r--    1 root     root            22 Apr  2 13:36 .dockerignore
-rw-rw-r--    1 root     root           272 Apr  2 13:36 [.gitignore]
drwxrwxr-x    2 root     root          4096 Apr  2 13:36 .gitlab
-rw-rw-r--    1 root     root            58 Apr  2 13:36 .gitlab-ci.yml
-rw-rw-r--    1 root     root            75 Apr  2 13:36 .gitmodules
-rw-rw-r--    1 root     root          2644 Apr  2 13:36 CMakeLists.txt
-rw-rw-r--    1 root     root           367 Apr  2 13:36 [CREDITS.md](http://credits.md/)
-rw-rw-r--    1 root     root           702 Apr  2 13:36 Dockerfile
-rw-rw-r--    1 root     root           295 Apr  2 13:36 LICENSE-3rdparty.csv
-rw-rw-r--    1 root     root         11342 Apr  2 13:36 [LICENSE.md](http://license.md/)
-rw-rw-r--    1 root     root          1852 Apr  2 13:36 Makefile
-rw-rw-r--    1 root     root          4871 Apr  2 13:36 [README.md]
drwxrwxr-x    3 root     root          4096 Apr  2 13:36 bin
drwxrwxr-x    2 root     root          4096 Apr  2 13:36 dd-trace-cpp
drwxrwxr-x    2 root     root          4096 Apr  2 13:36 doc
drwxrwxr-x    5 root     root          4096 Apr  2 13:36 example
drwxrwxr-x    4 root     root          4096 Apr  2 13:36 lab
-rw-rw-r--    1 root     root          4126 Apr  2 13:36 mascot.svg
drwxrwxr-x    2 root     root          4096 Apr  2 13:36 module
-rw-rw-r--    1 root     root          1233 Apr  2 13:36 nginx-module.cmake
-rw-rw-r--    1 root     root          1548 Apr  2 13:36 nginx-version-info.example
drwxrwxr-x    2 root     root          4096 Apr  2 13:36 src
drwxrwxr-x    6 root     root          4096 Apr  2 13:36 test
git submodule update --init --recursive
fatal: not a git repository (or any of the parent directories): .git
make: *** [Makefile:21: dd-trace-cpp/.git] Error 128

**Comment by dmehala** [comment]
Hi @monelgordillo 

Interesting. Did you download the source code, unzip it and run `NGINX_VERSION=1.22.1 make build` at the root? If yes, we always assumed developers/SRE would clone the repo and run the command.

If you can directly clone the repo (`git clone https://github.com/DataDog/nginx-datadog.git`), it should be working. Otherwise, we can always find a workaround.
