### ISSUE TITLE
Error: Executing invalid Datadog script

### ISSUE THREAD

**Issue by kevinneufeld** [DataDog/nginx-datadog#94]
After updating to the version `1.2.x` without appsec support we are seeing the following nginx errors in our logs:

```shell
2024/06/27 18:16:19 [error] 33#33: *2 Executing invalid Datadog script, client: 192.168.65.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
2024/06/27 18:16:19 [error] 33#33: *2 Executing invalid Datadog script, client: 192.168.65.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
2024/06/27 18:16:19 [error] 33#33: *2 Executing invalid Datadog script while logging request, client: 192.168.65.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
```

Logs and APM traces are published in the Datadog dashboard, but the fact that these errors occur for each request is a bit concerning.  Is there a new Datadog module setting we need to set?  

When we revert back to `v1.1.0` these errors are NOT present. 

Tech Specifications:
Alpine Linux amd64:`v3.20.0`
nginx: `v1.2.1`
nginx-datadog module: `v1.2.x`

**Comment by dmehala** [comment]
Hey @kevinneufeld

Thank you for reporting the issue. We are already aware of this issue and are working on a fix. Fortunately it is not harmful and don't prevent tracing.

**Comment by kevinneufeld** [comment]
Hey @dmehala, 
What is the ETA for getting a fixed release?

**Comment by dmehala** [comment]
Since the issue does not prevent tracing or appsec, there is no urgency to release a new version solely for this fix. The next release will follow our regular release cycle, which will likely occur in the coming months.

**Comment by afares-hims** [comment]
Any idea when is the next release? This is a blocker for us to add this module. Thanks!

**Comment by dmehala** [comment]
Tomorrow @afares-hims

**Comment by dmehala** [comment]
I encountered build issues for some version of NGINX, unfortunately it will not be today @afares-hims. I am working on fixing the issue this week.

**Comment by afares-hims** [comment]
No worries, thanks for the heads up!

**Comment by dmehala** [comment]
[New release](https://github.com/DataDog/nginx-datadog/releases/tag/v1.3.0) @afares-hims . Feel free to reach if there's any issue.

**Comment by afares-hims** [comment]
Thank you @dmehala! appreciate it.
