### ISSUE TITLE
"Executing invalid Datadog script" errors with every request

### ISSUE THREAD

**Issue by toadjaune** [DataDog/nginx-datadog#97]
# Description

For every request, 2 error log lines are generated, like those : 
```
2024/07/24 12:48:07 [error] 216792#216792: *120 Executing invalid Datadog script, client: 10.2.3.178, server: , request: "GET /health/ HTTP/1.1", host: "10.2.1.156"
2024/07/24 12:48:07 [error] 216792#216792: *120 Executing invalid Datadog script while logging request, client: 10.2.3.178, server: , request: "GET /health/ HTTP/1.1", host: "10.2.1.156"
```
Please note that despite the presence of those logs, the traces are correctly sent.

# System info

* Operating system : `Ubuntu 24.04 LTS`
* Kernel : `Linux <hostname> 6.8.0-1011-aws #12-Ubuntu SMP Fri Jun 21 18:30:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
* Nginx : `nginx/1.24.0 (Ubuntu)` / `1.24.0-2ubuntu7`
* nginx-datadog : `1.2.1`
* datadog agent version : `Agent 7.55.1 - Commit: 8ec9dff - Serialization version: v5.0.119 - Go version: go1.21.11`

# Minimal reproducing configuration

* Start with a fresh ubuntu 24.04 system
* Install the datadog agent with the one-liner [here](https://docs.datadoghq.com/getting_started/agent/#installation)
* `apt install nginx`
* Install the nginx-datadog module in `/usr/lib/nginx/modules/`
* Set the following in `nginx.conf` : 
```nginx
load_module modules/ngx_http_datadog_module.so;

user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;

events {
  worker_connections 768;
}

http {
  server {
    listen 80 default_server;
    listen [::]:80 default_server;

    stub_status; # triggers the extraneous log lines
    # return 204; # does not trigger the issue
  }
}
```
* `systemctl restart nginx`
* `curl -v localhost`
* See the error log lines in `/var/log/nginx/error.log`

I suspect that the reason why the `return` config line does not exhibit the bug is because of https://github.com/DataDog/nginx-datadog/issues/58 (they aren't traced and don't trigger this module's code)

**Comment by toadjaune** [comment]
After further testing, this seems to be a regression introduced by version `1.2.0` ; `1.1.0` does not exhibit the bug.

**Comment by skomp** [comment]
I guess this is the same issue. We receive these logs since upgrade to version 1.2.0 and 1.2.1, respectively.

```
2024/07/25 11:43:58 [error] 42#42: *141704 Executing invalid Datadog script while sending to client, client: 10.0.38.226, server: localhost, ...
2024/07/25 11:43:58 [error] 42#42: *141704 Condition expression for  directive at :0 evaluated to unexpected value "". Expected "on" or "off". Proceeding as if the value were "off". while sending to client
```

Tested on nginx 1.25.4 for 1.1.0 dd plugin, 1.26.0 for 1.1.0, 1.27.0 for dd plugin version 1.2.1.

**Comment by obukhov** [comment]
Observing same exact issue in version 1.2.0

**Comment by kneufeld-pbp** [comment]
It looks similar to my issue [#94](https://github.com/DataDog/nginx-datadog/issues/94), which has been merged and will be part of the next release, which we are waiting for. In the meantime, we have built the module ourselves from the `master` branch, and it appears to work without issue in our pre-production environments.

**Comment by toadjaune** [comment]
Indeed it does. Sorry for the duplicate !
